apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: workbc-small-grants-api
labels:
  template: workbc-small-grants-api
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: ${NAME}${SUFFIX}
  spec:
    replicas: 2
    selector:
      deploymentconfig: ${NAME}${SUFFIX}
    strategy:
      resources:
        requests:
          cpu: '100m'
        limits:
          cpu: '150m'
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: ${NAME}${SUFFIX}
      spec:
        containers:
        - image: ${NAME}:${TAG}
          name: workbc-small-grants-api
          ports:
          - containerPort: 8000
            protocol: TCP
          resources:
            requests:
              cpu: '100m'
            limits:
              cpu: '150m'
          env:
          - name: OPENSHIFT_NODEJS_ORIGIN_URL
            value: ${OPENSHIFT_NODEJS_ORIGIN_URL}
          - name: OPENSHIFT_NODEJS_CONFIRMATIONONE
            value: ${OPENSHIFT_NODEJS_CONFIRMATIONONE}
          - name: OPENSHIFT_NODEJS_CONFIRMATIONTWO
            value: ${OPENSHIFT_NODEJS_CONFIRMATIONTWO}
          - name: OPENSHIFT_NODEJS_CONFIRMATIONBCC
            value: ${OPENSHIFT_NODEJS_CONFIRMATIONBCC}
          - name: OPENSHIFT_NODEJS_LISTEMAIL
            value: ${OPENSHIFT_NODEJS_LISTEMAIL}
          - name: OPENSHIFT_NODEJS_NOTIFYEMAIL
            value: ${OPENSHIFT_NODEJS_NOTIFYEMAIL}
          - name: OPENSHIFT_NODEJS_CLIENT_CONFIRMATION_EMAIL
            value: ${OPENSHIFT_NODEJS_CLIENT_CONFIRMATION_EMAIL}
          - name: OPENSHIFT_NODEJS_CLIENT_CONFIRMATION_BCC
            value: ${OPENSHIFT_NODEJS_CLIENT_CONFIRMATION_BCC}
          - name: OPENSHIFT_NODEJS_CLIENT_LISTEMAIL
            value: ${OPENSHIFT_NODEJS_CLIENT_LISTEMAIL}
          - name: OPENSHIFT_NODEJS_CLIENT_NOTIFYEMAIL
            value: ${OPENSHIFT_NODEJS_CLIENT_NOTIFYEMAIL}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - workbc-small-grants-api
        from:
          kind: ImageStreamTag
          name: ${NAME}:${TAG}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: ${NAME}${SUFFIX}
  spec:
    ports:
    - name: api
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      deploymentconfig: ${NAME}${SUFFIX}
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: workbc-small-grants-api
- description: A name suffix used for all objects
  displayName: Suffix
  name: SUFFIX
  required: false
  value: ''
- description: Tag used for the image tags
  displayName: tag
  name: TAG
  required: true
  value: latest
- description: Email one to send confirmation emails (test)
  displayName: Confirmation email one
  name: OPENSHIFT_NODEJS_CONFIRMATIONONE
  required: false
  value: ''
- description: Email two to send confirmation emails (test)
  displayName: Confirmation email two
  name: OPENSHIFT_NODEJS_CONFIRMATIONTWO
  required: false
  value: ''
- description: BCC email to send confirmation emails
  displayName: Confirmation BCC email
  name: OPENSHIFT_NODEJS_CONFIRMATIONBCC
  required: false
  value: ''
- description: List email to send notification emails
  displayName: List email
  name: OPENSHIFT_NODEJS_LISTEMAIL
  required: false
  value: ''
- description: Notify email to send notification emails
  displayName: Notify email
  name: OPENSHIFT_NODEJS_NOTIFYEMAIL
  required: false
  value: ''
- description: The origin URL
  displayName: Workbc-small-grants api
  name: OPENSHIFT_NODEJS_ORIGIN_URL
  required: false
  value: ''
- description: Email to send client confirmation
  displayName: Notify email
  name: OPENSHIFT_NODEJS_CLIENT_CONFIRMATION_EMAIL
  required: false
  value: ''
- description: BCC email to send client confirmation emails
  displayName: Notify email
  name: OPENSHIFT_NODEJS_CLIENT_CONFIRMATION_BCC
  required: false
  value: ''
- description: List client email to send notification emails
  displayName: Notify email
  name: OPENSHIFT_NODEJS_CLIENT_LISTEMAIL
  required: false
  value: ''
- description: Notify client email to send notification emails
  displayName: Notify email
  name: OPENSHIFT_NODEJS_CLIENT_NOTIFYEMAIL
  required: false
  value: ''
